### PR TITLE
15 use common prefix for function names spo

### LINKED ISSUE #15: Use common prefix for function names (spo)?

### PR DESCRIPTION
**Pull request by Robinlovelace**
- **Replace all function names with spo_ (#15)**
- **Document, close #15**

### CODE REVIEW

**Comment by Robinlovelace** [comment]
What do you think of this @e-kotov ? Tried but failed to think of a better of affix that `spo`.

**Comment by e-kotov** [comment]
does `spod` seem too long? the letters are very close on the keyboard and there's autocomplete anyway.

**Comment by Robinlovelace** [comment]
`spod` sounds fine to me.

**Review by e-kotov — APPROVED** [review]

**Comment by Robinlovelace** [comment]
Thanks Egor! Just deleted the branch, final step in the branch, PR, Review, merge workflow: tidy up : )

**Comment by e-kotov** [comment]
@Robinlovelace ok, i will remove the branches in the future. I was hesitant to delete your branch)

**Comment by Robinlovelace** [comment]
👍 an even more cautious approach is to review and leave it to the person submitting the PR to merge, but that's over-cautious in this case. Looking forward to boshing some of the issues and getting {spannishoddata} ready to put out there in the not-too-distant future 🚀

**Pull request merged**
