### PR TITLE
more changes to README

### PR DESCRIPTION
**Pull request by eugenividal**
@Robinlovelace @e-kotov 

In this PR I rewrote the intro of the README mentioning the two versions of the data. I also changed the title of the subsection 'Estudios basicos' to 'OD data' (not sure if this is the best title for this) and included the OD package reference. The reference.bib file is attached to releases. Please approve only if you agree with the changes.

### CODE REVIEW

**Review by e-kotov — APPROVED** [review]
All good

**Comment by e-kotov** [comment]
What happened here though? https://github.com/Robinlovelace/spanishoddata/releases/tag/bib accident?

**Comment by eugenividal** [comment]
@e-kotov I thought you needed the 'reference.bib' file to make it work, so I put it in releases 🤷 Should I delete it from there? Thanks for the closing issues tip 👌. I will make use of # issue in the PRs next time

**Comment by e-kotov** [comment]
> so I put it in releases 🤷

@eugenividal Hmm, you can just include it in the repo itself, commmit and add as part of the PR. Do you want to try that?

**Comment by e-kotov** [comment]
You can also add the link to the references.bib in the readme, see example here https://github.com/e-kotov/rJavaEnv/blob/main/vignettes/why-rJavaEnv.qmd and cite the package in the appropriate place in the readme.

**Comment by Robinlovelace** [comment]
Looking good, many thanks Eugeni 🔥

**Pull request merged**
