### PR TITLE
Tests for #55

### PR DESCRIPTION
**Pull request by Robinlovelace**

### CODE REVIEW

**Comment by Robinlovelace** [comment]
Heads-up @e-kotov looking at this now...

**Review by e-kotov — APPROVED** [review]

**Comment by Robinlovelace** [comment]
Going to fix merge conflicts with 

```
git merge main
```

**Comment by Robinlovelace** [comment]
Heads-up @e-kotov will merge now.

**Review by e-kotov — COMMENTED** [review]
Made a few minor fixes, renamed the long functions, updated plot with package logic

**Pull request merged**
